name: Liquidice Gem Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # rubocop:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/sparklemotion/nokogiri-test:mri-3.2
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - run: bundle install --local || bundle install
  #     - run: bundle exec rake rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0',  '3.2']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec

  #  - name: Release Gem
  #       if: contains(github.ref, 'refs/tags/v')
  #       uses: cadwallion/publish-rubygems-action@master
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #         RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
  #         RELEASE_COMMAND: rake release
